esphome:
  name: sonoff-basic-2
  friendly_name: Sonoff Basic 2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "W6fW0KOpYtmNjBL4IHxE6tCDD0ph6398XqNkkYGZPTs="

ota:
  password: "b9339b5c6e711b9bad0c8256be2b4590"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Basic-2 Fallback Hotspot"
    password: "6IdvTtq7JjBT"

captive_portal:
    