# device specific settings
substitutions:
  device_name: sonoffbasicr2nr2
  friendly_name: Sonoff BASIC R2 nr2
  device_ip: 192.168.11.137
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotsp'
    password: !secret wifi_password

captive_portal:

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: '${device_name} button'
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: '${device_name} Relay'
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

# firmware version
text_sensor:
  - platform: version
    name: '${device_name}_version'