esphome:
  name: sonoff-basic-r2
  friendly_name: Sonoff BASIC R2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SWQ4F0Pclm1qw/88Lbl3KuHlsOSVcef/iwqBFYxP9Z4="

ota:
  password: "6219dea36f6c1d7dd7a86e396ca09e8b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Basic-R2 Fallback Hotspot"
    password: "vrDZEQJoa04v"

captive_portal:
    