esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GYbtEjsGIHCKjUal1Jh3zmOySlXuZt2Cs3o5C+Rj9TI="

ota:
  - platform: esphome
    password: "0c1f0ecb2da64baf999ba261efa222ad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "igYYgEgIuC3Q"

captive_portal:
    