# device specific settings
substitutions:
  device_name: wroom-daniel
  friendly_name: Wroom-Daniel
  device_ip: 192.168.11.199

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotspot'
    password: !secret wifi_password

web_server:
  auth:
    username: admin
    password: !secret webserver_password

captive_portal:

# wifi signal and uptime
sensor:
  - platform: wifi_signal
    name: '${device_name}_wifi_signal'
    update_interval: 60s
  - platform: uptime
    name: '${device_name}_uptime'

# firmware version
text_sensor:
  - platform: version
    name: '${device_name}_version'

switch:
  - platform: restart
    name: ${device_name} restart

binary_sensor:
  - platform: status
    name: ${device_name} status  
    