# device specific settings
substitutions:
  device_name: nodemcu-v3
  friendly_name: NodeMcu v3
  device_ip: 192.168.11.124

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotspot'
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password

sensor:
  - platform: wifi_signal
    name: '${device_name}_wifi_signal'
    update_interval: 60s
  - platform: uptime
    name: '${device_name}_uptime'

# switch relay
switch:
  - platform: template
    name: '${device_name}_switch'
    optimistic: true
    id: fakebutton
    restore_mode: ALWAYS_ON
    turn_on_action:
    - light.turn_on: led
    turn_off_action:
    - light.turn_off: led
  - platform: restart
    name: '${device_name}_Restart'

# toggle button & state
binary_sensor:
  - platform: gpio
    name: '${device_name}_button'
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: fakebutton
  - platform: status
    name: '${device_name}_Status'
    
# firmware version
text_sensor:
  - platform: version
    name: '${device_name}_version'
  - platform: wifi_info
    ip_address:
      name: ${device_ip}
    ssid:
      name: !secret wifi_ssid
    bssid:
      name: !secret wifi_ssid

# set led state
output:
  - platform: esp8266_pwm
    id: nodemcu_led
    pin:
      number: GPIO2
      inverted: True

# led state
light:
  - platform: monochromatic
    name: '${device_name}_bue_led'
    output: nodemcu_led
    id: led
