# device specific settings
substitutions:
  device_name: sonoffbasicr2nr1
  friendly_name: Sonoff BASIC R2 nr1
  device_ip: 192.168.11.212

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotsp'
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password

# Device Specific Config
# get sensor measurements
sensor:
  - platform: wifi_signal
    name: '${device_name}_wifi_signal'
    update_interval: 60s
  - platform: uptime
    name: '${device_name}_uptime'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name}_Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${device_name}_Status"

switch:
  - platform: gpio
    name: "${device_name}_Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON
  - platform: restart
    name: "${device_name}_Restart"

status_led:
  pin:
    number: GPIO13
    inverted: yes

# firmware version
text_sensor:
  - platform: version
    name: '${device_name}_version'