---

# GPIO #	Component
# GPIO00	Button 1
# GPIO01	CSE7766 Tx
# GPIO02	None
# GPIO03	CSE7766 Rx
# GPIO04	None
# GPIO05	None
# GPIO09	None
# GPIO10	None
# GPIO12	Relay_i 1
# GPIO13	Led_i 1
# GPIO14	None
# GPIO15	User
# GPIO16	User
# GPIO17	User


# device specific settings
substitutions:
  device_name: sonoffpowr3boil
  friendly_name: Sonoff Pow R3 boiler
  device_ip: 192.168.11.119

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotspot'
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password

uart:
  rx_pin: RX
  baud_rate: 4800

# firmware version
text_sensor:
  - platform: version
    name: '${device_name}_version'
  - platform: wifi_info
    ip_address:
      name: ${device_ip}
    ssid:
      name: !secret wifi_ssid

sensor:
  - platform: uptime
    name: '${device_name}_Uptime'
  - platform: wifi_signal
    name: '${device_name}_WiFi Signal'
    update_interval: 60s
  - platform: uptime
    name: '${device_name}_uptime'
  - platform: cse7766
    current:
      name: '${device_name}_current'
      filters:
        - throttle_average: 10s
    voltage:
      name: '${device_name}_voltage'
      filters:
        - throttle_average: 10s
    power:
      name: '${device_name}_power'
      filters:
        - throttle_average: 10s
      id: power
      on_value_range:
        - above: 2.0
          then:
            - light.turn_on: led
        - below: 1.0
          then:
            - light.turn_off: led
    energy:
      name: '${device_name}_energy'
      filters:
        - throttle_average: 10s    

# toggle button & state
binary_sensor:
  - platform: status
    name: '${device_name}_Status'
  - platform: gpio
    name: '${device_name}_button'
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: restart
    name: "${device_name}_Restart"
  - platform: template
    name: '${device_name}_switch'
    optimistic: true
    id: fakebutton
    restore_mode: ALWAYS_ON
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_ON

# set blue led state
output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

# blue led state
light:
  - platform: monochromatic
    name: '${device_name}_bue_led'
    output: pow_blue_led
    id: led