
# device specific settings
substitutions:
  device_name: sonoff-s26-plug2
  friendly_name: Sonoff S26 plug2
  device_ip: 192.168.11.215

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m
  board_flash_mode: dout

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'sonoff-plug2_Fallback_Hotspot'
    password: !secret wifi_password

captive_portal:

status_led:
  pin:
    number: GPIO13
    inverted: false

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${device_name} Status"

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${device_name} Uptime"

switch:
  - platform: gpio
    name: "${device_name} Relay"
    pin: GPIO12
    id: "relay"
  - platform: restart
    name: "${device_name} Restart"

text_sensor:
  - platform: version
    name: '${device_name}_version'
  - platform: wifi_info
    ip_address:
      name: ${device_ip}
    ssid:
      name: !secret wifi_ssid
    bssid:
      name: !secret wifi_ssid


