# device specific settings
substitutions:
  device_name: sonoff-re5v-1c
  friendly_name: Sonoff RE5V-1C 
  device_ip: 192.168.11.195

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp8285
  restore_from_flash: true

logger:
  esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_Fallback_Hotspot'
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password

time:
  - platform: homeassistant
    id: homeassistant_time
 
text_sensor:
  - platform: version
    name: '${device_name}_version'
  - platform: wifi_info
    ip_address:
      name: ${device_ip}
    ssid:
      name: !secret wifi_ssid
    bssid:
      name: !secret wifi_ssid
 
sensor:
  - platform: uptime
    name: '${device_name}_Uptime'
  - platform: wifi_signal
    name: '${device_name}_WiFi Signal'
    update_interval: 60s
 
switch:
  - platform: restart
    name: "${device_name} Restart"
 
binary_sensor:
  - platform: status
    name: "Status_${device_name}"
    