
# device specific settings
substitutions:
  device_name: sonoff-s26-plug1
  friendly_name: Sonoff S26 plug1
  device_ip: 192.168.11.215

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m
  board_flash_mode: dout

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.11.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'sonoff-plug1_Fallback_Hotspot'
    password: !secret wifi_password

captive_portal:

status_led:
  pin:
    number: GPIO13
    inverted: false

web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S26_1 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S26_1 Status"

sensor:
  - platform: wifi_signal
    name: "sonoffs26_1 WiFi Signal"
    update_interval: 60s
switch:
  - platform: gpio
    name: "Sonoff S26_1 Relay"
    pin: GPIO12
    id: "relay"
  - platform: restart
    name: "sonoffs26_1 Restart"
    